package edu.stanford.bmir.protegex.chao.annotation.api;

import java.util.Collection;

import edu.stanford.bmir.protegex.chao.ontologycomp.api.Ontology_Class;
import edu.stanford.bmir.protegex.chao.ontologycomp.api.Timestamp;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: NewEntityProposal
 *
 * @version generated on Wed Dec 09 14:44:45 PST 2009
 */
public interface NewEntityProposal extends Proposal {

    // Slot annotates

    Collection<AnnotatableThing> getAnnotates();

    boolean hasAnnotates();

    void addAnnotates(AnnotatableThing newAnnotates);

    void removeAnnotates(AnnotatableThing oldAnnotates);

    void setAnnotates(Collection<? extends AnnotatableThing> newAnnotates);


    // Slot associatedAnnotations

    Collection<Annotation> getAssociatedAnnotations();

    boolean hasAssociatedAnnotations();

    void addAssociatedAnnotations(Annotation newAssociatedAnnotations);

    void removeAssociatedAnnotations(Annotation oldAssociatedAnnotations);

    void setAssociatedAnnotations(Collection<? extends Annotation> newAssociatedAnnotations);


    // Slot author

    String getAuthor();

    boolean hasAuthor();

    void setAuthor(String newAuthor);


    // Slot body

    String getBody();

    boolean hasBody();

    void setBody(String newBody);


    // Slot contactInformation

    String getContactInformation();

    boolean hasContactInformation();

    void setContactInformation(String newContactInformation);


    // Slot context

    String getContext();

    boolean hasContext();

    void setContext(String newContext);


    // Slot created

    Timestamp getCreated();

    boolean hasCreated();

    void setCreated(Timestamp newCreated);


    // Slot definition

    LinguisticEntity getDefinition();

    boolean hasDefinition();

    void setDefinition(LinguisticEntity newDefinition);


    // Slot entityId

    String getEntityId();

    boolean hasEntityId();

    void setEntityId(String newEntityId);


    // Slot hasStatus

    Status getHasStatus();

    boolean hasHasStatus();

    void setHasStatus(Status newHasStatus);


    // Slot modified

    Timestamp getModified();

    boolean hasModified();

    void setModified(Timestamp newModified);


    // Slot parent

    Collection<Ontology_Class> getParent();

    boolean hasParent();

    void addParent(Ontology_Class newParent);

    void removeParent(Ontology_Class oldParent);

    void setParent(Collection<? extends Ontology_Class> newParent);


    // Slot preferredName

    LinguisticEntity getPreferredName();

    boolean hasPreferredName();

    void setPreferredName(LinguisticEntity newPreferredName);


    // Slot reasonForChange

    String getReasonForChange();

    boolean hasReasonForChange();

    void setReasonForChange(String newReasonForChange);


    // Slot related

    String getRelated();

    boolean hasRelated();

    void setRelated(String newRelated);


    // Slot subject

    String getSubject();

    boolean hasSubject();

    void setSubject(String newSubject);


    // Slot synonym

    Collection<LinguisticEntity> getSynonym();

    boolean hasSynonym();

    void addSynonym(LinguisticEntity newSynonym);

    void removeSynonym(LinguisticEntity oldSynonym);

    void setSynonym(Collection<? extends LinguisticEntity> newSynonym);

    void delete();
}
