package edu.stanford.bmir.protegex.chao.annotation.api;

import java.util.Collection;

import edu.stanford.bmir.protegex.chao.ontologycomp.api.Reviewer;
import edu.stanford.bmir.protegex.chao.ontologycomp.api.Timestamp;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: ReviewRequest
 *
 * @version generated on Wed Dec 09 14:44:45 PST 2009
 */
public interface ReviewRequest extends Annotation {

    // Slot annotates

    Collection<AnnotatableThing> getAnnotates();

    boolean hasAnnotates();

    void addAnnotates(AnnotatableThing newAnnotates);

    void removeAnnotates(AnnotatableThing oldAnnotates);

    void setAnnotates(Collection<? extends AnnotatableThing> newAnnotates);


    // Slot associatedAnnotations

    Collection<Annotation> getAssociatedAnnotations();

    boolean hasAssociatedAnnotations();

    void addAssociatedAnnotations(Annotation newAssociatedAnnotations);

    void removeAssociatedAnnotations(Annotation oldAssociatedAnnotations);

    void setAssociatedAnnotations(Collection<? extends Annotation> newAssociatedAnnotations);


    // Slot author

    String getAuthor();

    boolean hasAuthor();

    void setAuthor(String newAuthor);


    // Slot body

    String getBody();

    boolean hasBody();

    void setBody(String newBody);


    // Slot completed

    boolean getCompleted();

    boolean hasCompleted();

    void setCompleted(boolean newCompleted);


    // Slot context

    String getContext();

    boolean hasContext();

    void setContext(String newContext);


    // Slot created

    Timestamp getCreated();

    boolean hasCreated();

    void setCreated(Timestamp newCreated);


    // Slot deadline

    String getDeadline();

    boolean hasDeadline();

    void setDeadline(String newDeadline);


    // Slot hasStatus

    Status getHasStatus();

    boolean hasHasStatus();

    void setHasStatus(Status newHasStatus);


    // Slot modified

    Timestamp getModified();

    boolean hasModified();

    void setModified(Timestamp newModified);


    // Slot related

    String getRelated();

    boolean hasRelated();

    void setRelated(String newRelated);


    // Slot reviewer

    Reviewer getReviewer();

    boolean hasReviewer();

    void setReviewer(Reviewer newReviewer);


    // Slot subject

    String getSubject();

    boolean hasSubject();

    void setSubject(String newSubject);

    void delete();
}
