package edu.stanford.bmir.protegex.chao.annotation.api;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Status
 *
 * @version generated on Wed Dec 09 14:44:45 PST 2009
 */
public interface Status {

    // Slot description

    String getDescription();

    boolean hasDescription();

    void setDescription(String newDescription);

    void delete();
}
