package edu.stanford.bmir.protegex.chao.annotation.api.impl;

import edu.stanford.bmir.protegex.chao.annotation.api.Status;
import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.Instance;
import edu.stanford.smi.protege.model.Slot;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Status
 *
 * @version generated on Wed Dec 09 14:44:45 PST 2009
 */
public class DefaultStatus extends AbstractWrappedInstance
         implements Status {

    public DefaultStatus(Instance instance) {
        super(instance);
    }


    public DefaultStatus() {
    }

    // Slot description

    public String getDescription() {
        return (String) getWrappedProtegeInstance().getOwnSlotValue(getDescriptionSlot());
    }


    public Slot getDescriptionSlot() {
        final String name = "description";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasDescription() {
        return hasSlotValues(getDescriptionSlot());
    }


    public void setDescription(String newDescription) {
        setSlotValue(getDescriptionSlot(), newDescription);
    }
}
