package edu.stanford.bmir.protegex.chao.annotation.api;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: LinguisticEntity
 *
 * @version generated on Wed Dec 09 15:45:51 PST 2009
 */
public interface LinguisticEntity {

    // Slot label

    String getLabel();

    boolean hasLabel();

    void setLabel(String newLabel);


    // Slot language

    String getLanguage();

    boolean hasLanguage();

    void setLanguage(String newLanguage);

    void delete();
}
